export const COLLEGES = [
  "A J Institute Of Engineering And Technology, Boloor Village, Mangalore (2016-17)",
  "Acharya Institute of Technology, Jindal Nagar, Bangalore",
  "Acharya N.R.V School of Architecture, Soladevanahalli, Bangalore",
  "Acharya Patashala Rural College of Engineering, Somanahalli, Bangalore.",
  "ACS College of Engineering, Bangalore",
  "Adarsha Institute of Technology, Devanahalli taluk, Bangalore Rural",
  "Adhichunchanagiri Institute of Technology, Chikkamagalur",
  "Adichunchanagiri University (Formerly BGSIT), Nagamangala Taluk, Mandya Dist.",
  "Adithya Academy of Architecture and Design, Yalahanka, Bangalore (2015-16)",
  "AGM Rural Engineering College, Varur, Hubli",
  "Akshaya Institute Of Technology, Tumkur",
  "Alliance University, Bangalore",
  "Alpha College of Engineering, Bangalore",
  "Alva`s Institute of Engineering and Technology, Moodabidre",
  "Alva`s Institute of Engineering and Technology, Moodabidri, Dakshina Kannada",
  "AMC Engineering College, Bannerghatta Road, Bangalore",
  "Amrutha Institute of Engineering & Management Science, Bidadi, Ramanagaram",
  "Angadi Institute Of Technology & Management, Belgaum",
  "Angadi School of Architecture, Belgaum",
  "Anjuman Engineering College, Bhatkal (Religious Minority) (MUSLIM)",
  "ATME College of Engineering, Mysore",
  "Atria Institute of Technology, Anandanagar, Hebbal PO, Bangalore",
  "B L D E A`s V.P. Dr. P. G. Hallakatti College of Engineering and Technology, Bijapur",
  "B M S College of Architecture, Basvanagudi, Bangalore",
  "B M S School of Architecture, Yelahanka, Bangalore",
  "B N M Institute of Technology, Bangalore",
  "B.M.S College of Engineering (Evening), Bangalore.",
  "B.M.S. College of Engineering, Bangalore",
  "B.T.L Institute of Technology & Management, Bommasandra, Bangalore",
  "B.V. B. College of Engineering and Technology, Hubli",
  "Bahubali College of Engineering, Shravanabelagola (Religious Minority) (JAIN)",
  "Ballari Institute of Technology and Management, Bellary",
  "Bangalore College of Engineering & Technology, Chandapura, Bangalore",
  "Bangalore Institute of Technology, Bangalore",
  "Bangalore Technological Institute, Bangalore.",
  "Bapuji Institute of Engineering and Technology, Davanagere",
  "Basava Engineering School of Technology, Vijayapura (2017-18)",
  "Basavakalyan Engineering College, Basavakalyan",
  "Basaveswara Engineering College, Bagalkote",
  "Beary’s Institute of Technology, Mangalore (Religious Minority) (MUSLIM)",
  "Bearys Enviro-Architecture Design School, Boliyar, Mangalore (2015-16)",
  "BGS School of Architecture and Planning, Nithyanandanagar, Bangalore (2015-16)",
  "Bheemanna Khandre Institute of Technology, Bhalki",
  "Biluru Gurubasava Mahaswamiji Institute of Technology, Mudhol, Bagalkote",
  "BMS Institute of Technology and Management, Yelahanka, Bangalore",
  "Brindavan College of Engineering, Yalahanka, Bangalore",
  "Brindavana College of Architecture, Bangalore (2016-17)",
  "C Byregowda Institute Of Technology, Kolar",
  "Cambridge Institute of Technology, K.R.Puram, Bangalore",
  "Cambridge Institute of Technology-North Campus, Devanahalli(TQ), Bangalore",
  "Canara Engg College, Banjara, Bantawal (Religious Minority) (KONKANI)",
  "Cauvery Institute of Technology, Siddaiahna Koppalu Gate, Yelihur(P), Kothathi(H)",
  "Channa Basaveshwara Institute of Technology, Gubbi Tumkur Dt.",
  "City Engineering College, Raghuvanahalli, Kanakapura Main Road, Bangalore",
  "CMR Institute of Technology, Kundala Halli Village, Bangalore",
  "CMR University School of Architecture, Bangalore (2015-16)",
  "CMR University, Chagalatti, Bangalore",
  "Coorg Institute of Technology, Kunda, Ponnampet",
  "Dayanand Sagar Academy of Technology, Kanakapura Road, Bangalore",
  "Dayanand Sagar College of Engineering, Kumarswamy Layout, Bangalore",
  "Dayananda Sagar College of Engineering, Bangalore",
  "Dayananda Sagar University, Hosur Road, Bangalore",
  "DONBOSCO Institute of Technology, Kumbalagodu, Bangalore",
  "Dr. Ambedkar Institute of Technology, Bangalore",
  "Dr. Sri.Sri.Sri. Shivakumara Mahaswamy College of Engineering, Byranayakanahalli, Bangalore (R)",
  "Dr. T. Thimmaiah Institute of Technology, Oorgaum, K.G.F",
  "East Point College of Engineering & Technology, Bangalore",
  "East West College of Engineering, Yelahanka, Bangalore (2015-16)",
  "East West Institute of Technology, Magadi Main Road, Bangalore.",
  "East West School of Architecture, Near Anjanagar, Bangalore",
  "Ekalavya Institute Of Technology, Chamarajanagar",
  "G M Institute of Technology, Davangere",
  "G. Madegowda Institute of Technology, Maddur, Madya Dist",
  "G.S.S.S. College of Engineering for Women, Mysore",
  "Ghousia Engineering College, Ramanagar (Religious Minority) (MUSLIM)",
  "Girijabai Sail Institute of Technology, Karwar",
  "Gitam School Of Technology, Nagadenahalli, Doddaballapur(T)",
  "Global Academy of Technology, Rajarajeshwari Nagr, Bangalore",
  "Gopalan College of Engineering & Management, K.R.Puram, Bangalore",
  "Gopalan School of Architecture and Planning, K R Puram, Bangalore",
  "Government Engineering College, Bidar",
  "Government Engineering College, Challekere",
  "Government Engineering College, Gangavathi",
  "Government Engineering College, Hassan",
  "Government Engineering College, Haveri",
  "Government Engineering College, Huvinahadagali",
  "Government Engineering College, Karwar",
  "Government Engineering College, KR Pet",
  "Government Engineering College, Kushalnagar",
  "Government Engineering College, MosaleHosahalli",
  "Government Engineering College, Raichur",
  "Government Engineering College, Ramanagar",
  "Government Engineering College, Talakal",
  "Government Engineering, Chamarajanagar",
  "Gurunanak Dev Engineering College, Bidar (Religious Minority) (SIKH)",
  "H.K.B.K. College of Engineering, Bangalore (Religious Minority) (MUSLIM)",
  "H.K.E.'s S.L.N. College of Engineering, Raichur",
  "H.M.S. Institute of Technology, Tumkur",
  "Hirasugar Institute of Technology, Nidasosi",
  "HMS School of Architecture, Tumkur (2015-16)",
  "Impact College of Engineering and Applied Sciences, Kodigehalli, Bangalore",
  "Impact School of Architecture, Impact Campus, Sahakara Nagar, Bangalore",
  "Islamia Institute of Technology, Bangalore",
  "J.S.S. Academy of Technical Education, Bangalore",
  "Jain Acharya Gundharnandi Maharaj Institute of Technology, Jamakandi, Bagalkot Dist",
  "Jain College of Engineering & Technology, Hubballi. (2017-18)",
  "Jain College of Engineering and Research, Udyambhag, Belgaum (2018-19)",
  "Jain College of Engineering, Belagavi",
  "Jain College of Engineering, Machche, Belgaum",
  "Jain Institute of Technology, Davanagere",
  "Jain University, School of Engineering and Technology, Kanakapura Road, (Deemed)",
  "Jawaharlal Nehru National College of Engineering, Shimoga",
  "Jnanavikasa Institute of Technology, Bidadi",
  "JSS Science and Technology University (Formerly SJCE), Mysore",
  "Jyothi Institute of Technology, Kanakapura Road, Bangalore",
  "K L E Dr. M S Sheshagiri College of Engineering and Technology, Belgaum",
  "K L E S`s K L E College of Engineering and Technology, Chikkodi, Belgaum Dist.",
  "K N S Institute of Technology, Bangalore",
  "K S School of Architecture, Bangalore (2015-16)",
  "K.L.S. Gogte Institute of Technology, Belgaum",
  "K.L.S's Vishwanathrao Deshpande Rural Institute of Technology, Haliyala",
  "K.S School Of Engineering, Mallasandra, Bangalore.",
  "K.S. Institute of Technology, Raghuvanahalli, Kanakapura Main Raod, Bangalore",
  "Kalpataru Institute of Technology, Tiptur",
  "Karavali Institute, of Technology, Neermarga, Mangalore",
  "KCT Engineering College, Gulbarga (Religious Minority) (MUSLIM)",
  "Nadgir Institute of Engineering and Technology, Jindal Nagar, Bangalore (2016-17)",
  "Nagarjuna College of Engineering. & Technology, Bangalore Rural Dist",
  "National Institute of Engineering (Evening), Mysore",
  "Navkis College of Engineering, Hassan",
  "Navodaya Institute of Technology, Raichur",
  "New Horizon College of Engineering, Bangalore (Linguistic Minority)",
  "New Horizon College of Engineering, Varthur, Bangalore (Linguistic Minority) (SINDHI)",
  "NIE Institute of Technology, Mysore",
  "Nitte Institute of Architecture, Bangalore (2016-17)",
  "NITTE Institute of Architecture, Nitte University, Mangalore",
  "Nitte Meenakshi Institute of Technology, Bangalore",
  "P E S University (Electronic City Campus), Bangalore",
  "P E S University (Formerly PESIT), Bangalore",
  "P.A. College of Engineering, Kairangal, Bantwala",
  "P.A. College of Engineering, Kairangal, Bantwala Tq. (Religious Minority) (MUSLIM)",
  "P.D.A College of Engg. Gulbarga",
  "P.E.S College of Engineering, Mandya",
  "PES Institute of Technology & Management, Shimoga",
  "Prasanna College of Engineering and Technology, Ujire, D.K",
  "Presidency University, Yelahanka, Bangalore",
  "Proudadevaraya Institute of Technology, Hospet",
  "R L Jalappa Institute of Technology, Doddaballapura, Bangalore Rural",
  "R N S Institute of Technology, Bangalore",
  "R N S School of Architecture, Bangalore (2017-18)",
  "R R School of Architecture, Chickbanavara, Bangalore",
  "R.R. Institute of Technology, Chikkabanavara, Bangalore",
  "R.T.E Socity's Rural Engineering College, Hulkoti",
  "R.V. College of Architecture, 4th Block, BSK 6th Stage, Bangalore",
  "R.V. College of Engineering, Bangalore",
  "Rai Technology University, Mallohalli(V), Doddaballapur(T)",
  "Rajarajeshwari College of Engineering, Bangalore",
  "Rajeev Institute of Technology, Hassan",
  "Rajiv Gandhi Institute of Technology, Bangalore",
  "Rao Bahadur Y. Mahabaleswarappa Engineering College, Bellary",
  "Reva University, Bangalore",
  "S.G. Balekundri Institute of Technology, Belgaum",
  "S.J.C. Institute of Technology, Chickballapur",
  "S.J.M. Institute of Technology, Chitradurga",
  "S.T.J. Institute of Technology, Ranebennur",
  "Sahyadri College of Engineering and Management, Mangalore",
  "Sai Vidya Institute of Technology, Doddaballapur Road, Bangalore",
  "Sambhram Institute of Technology, Bangalore",
  "Sampoorna Institute of Technology and Research, Channapattana",
  "Saptagiri College of Engineering, Bangalore",
  "School of Architecture B L D E A's V.P. Dr. P. G. Hallakatti College of Engg. and Tech., Vijayapura",
  "School of Architecture K.L.S. Gogte Institute of Technology, Belgaum",
  "School of Architecture P.D.A College of Engg. Gulbarga",
  "School of Architecture Srinivas inst. of tech., Mangalore",
  "School of Architecture University Visvesvaraya College of Engineering, Bangalore (Govt.)",
  "School of Architecture, Dayanand Sagar Academy of Technology, Kanakapura Road, Bangalore (2016-17)",
  "School of Architecture, Dayanand Sagar College of Engineering, Bangalore",
  "School of Architecture, M.S.Ramaiah Institute of Technology, Bangalore (2016-17)",
  "School of Architecture Siddaganga Institute of Technology, Tumkur",
  "SDM Inst. of Tech., Ujire, Dakshina Kannada (Linguistic Minority) (TULU)",
  "SEA College of Engineering & Technology, Virgonagar, K.R.Puram, Bangalore",
  "Secab Institute of Engineering and Technology, Vijayapura (Religious Minority) (MUSLIM)",
  "Sha-Shib College of Engineering, Chikkaballapura",
  "Shaikh College of Engineering & Technology, Belgaum",
  "Sharnabasava University (Formerly Godutai College for Women), Kalaburagi",
  "Sharnabasava University (Formerly Appa Inst. of Tech.), Brahmpur, Kalaburagi",
  "Shetty Institute of Technology, Gulbarga",
  "Shreedevi Institute of Technology, Kenjar, Mangalore",
  "Shri Madhwa Vadiraja Institute of Technology & Management, Bantakl",
  "Shridevi Institute of Engineering & Technology, Tumkur-Sira Road, Maralenahally, Tumakuru (2017-18)",
  "Siddaganga Institute of Technology, Tumkur",
  "Sir M V School of Architecture, Hunsamaranahalli, Bangalore (2017-18)",
  "Sir M. Visveswarayya Institute of Technology, Bangalore",
  "SJB School of Achitecture & Planning, Uthrahalli Road, Kengeri, Bangalore",
  "SKSJTI Evening College, Bangalore",
  "SKSJTI, Bangalore",
  "Smt. Kamala and Sri Venkappa M. Agadi College of Engg. and Tech., Lakshmeshwara, Gadag Dt.",
  "Sri Basaveshwara Institute of Technology, Tiptur (2017-18)",
  "Sri Dharmasthala Manjunatheswara Engineering College, Dharwad (Linguistic Minority) (TULU)",
  "Sri Jagadguru Balagangadharanatha Swamiji Institute of Technology, Bangalore",
  "Sri Jayachamarajendra College of Engineering (Evening), Mysore (Private Un-aided)",
  "Sri Jayachamarajendra College of Engineering, Mysore",
  "Sri Krishna Institute of Technology, Bangalore",
  "Sri Sai Ram College of Engineering, Anekal, Bangalore",
  "Sri Siddartha Institute of Technology, Tumkur (Deemed)",
  "Sri Venkateshwara College of Engineering, Bangalore",
  "Sri Vidya Vinayaka Institute of Technology, Vinayakanagar, Bangalore",
  "Sri Vinayaka Institute of Technology, Coromandel Post, K.G.F (2015-16)",
  "Srinivas Institute of Technology, Mangalore",
  "Srinivas University (2017-18)",
  "St. Joseph Engineering College, Mangalore",
  "T. John Engineering College, Bangalore",
  "The National Institute of Engineering, Mysore",
  "The Oxford College of Engineering, Bangalore (Linguistic Minority) (TELUGU)",
  "The Oxford School of Architecture, Bangalore (2015-16) (Minority)",
  "Tontadarya College of Engineering, Gadag",
  "University BDT College of Engineering, Davangere",
  "University Visvesvaraya College of Engineering, K.R. Circle, Bangalore",
  "University Visvesvaraya College of Engineering (Evening), Bangalore",
  "V S M Institute of Technology, Nippani",
  "Veerappa Nisty Engineering College, Shorapur, Yadagiri",
  "Vemana Institute of Technology, Bangalore",
  "Vidya Vardhaka College of Engineering, Mysore",
  "Vidya Vikas Institute of Engineering & Technology, Mysore",
  "Vijaya Vitala Institute Of Technology, Bangalore",
  "Vivekananda College of Engineering & Technology, Puttur",
  "Vivekananda Institute of Technology, Bangalore",
  "Wadiyar Centre For Architecture (Formerly CFA), Mysuru",
  "Yellamma Dasappa Institute of Technology, Raghuvanahalli, Kanakapura Main Road, Bangalore",
  "Yenepoya Institute Of Technology (Formerly Dr. MVSIT), Moodabidre, Mangalore (Tq)",
];

export const EVENTS = [
  {
    name: "Learn from My Mistakes: CEO Lessons Learned",
    speaker: "Suyog Shetty (Growth of Niveus)",
    description: "Ground Floor Seminar Hall",
    date: "14th June",
    time: "10:00 am",
    type: "Talk",
    seats: 60,
  },
  {
    name: "The Multiverse of OS: A Deep Dive into Dual Boot, VMs, and Containers",
    speaker: "Nibraz Rehman",
    description: "Ground Floor Seminar Hall",
    date: "14th June",
    time: "11:15 am",
    type: "Talk",
    seats: 60,
  },
  {
    name: "DevOps Fundamentals: Building a Strong Foundation",
    speaker: "Sagar Vaidya",
    description: "Skill Lab - 1",
    date: "14th June",
    time: "01:45 pm",
    type: "Master Class",
    seats: 60,
  },
  {
    name: "Level Up Your Web3 Game using Smart Contracts",
    speaker: "Subodh (Ethreal)",
    description: "Skill Lab - 2",
    date: "14th June",
    time: "01:45 pm",
    type: "Master Class",
    seats: 60,
  },
  {
    name: "Something Interesting 👀",
    speaker: "To be revealed soon",
    description:
      "Strategies and techniques for effective damage control in various situations.",
    date: "15th June",
    time: "09:30 am",
    type: "Talk",
    seats: 60,
  },
  {
    name: "Unlock Your Earning Potential: From Engineering to Corporate",
    speaker: "Nikhil Raj",
    description: "Ground Floor Seminar Hall",
    date: "15th June",
    time: "10:30 am",
    type: "Talk",
    seats: 60,
  },
  {
    name: "From Coastal Town to IT Hub: The Rise of Mangalore's IT Industry",
    speaker: "Shashir Shetty (Mod), Shihab Kalander, John Fernandes",
    description: "Ground Floor Seminar Hall",
    date: "15th June",
    time: "11:30 am",
    type: "Panel Discussion",
    seats: 60,
  },
  {
    name: "Cracking the MAANG Code: What It Takes to Get Hired in Top IT Companies",
    speaker: "Nikhil Raj (mod), Prasanna, Balakrishnan",
    description: "Ground Floor Seminar Hall",
    date: "15th June",
    time: "01:45 pm",
    type: "Panel Discussion",
    seats: 60,
  },
  {
    name: "10X Your API Productivity: Mastering APIs using Postman",
    speaker: "Mohit Tahiliani",
    description: "Skill Lab 1",
    date: "15th June",
    time: "02:30 pm",
    type: "Master Class",
    seats: 60,
  },
  {
    name: "GEN AI for Dummies: A Beginner's Guide to LLMS",
    speaker: "Akshay Kumar U",
    description: "Skill Lab 2",
    date: "15th June",
    time: "02:30 pm",
    type: "Master Class",
    seats: 60,
  },
];
